# docker-compose.yml
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - PORT=4000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - PORT=5173
