services:
  - type: web
    name: tasky-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
